server:
  AppVersion: 1.0.0
  Port: 0.0.0.0:8080
  SSL: true

postgres:
  #  host: "postgres"
  #  port: "5432"
  #  user: "erp_user"
  #  password: "erp_pass"
  #  dbname: "erp_db"
  #  timezone: "Asia/Ho_Chi_Minh"
  # DBSource: postgresql://neondb_owner:npg_tkKa6Gfspq7w@ep-proud-sound-a49dcdxx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require&TimeZone=Asia/Ho_Chi_Minh
  DBSource: postgresql://192.168.1.58:5432/erp_db?user=erp_user&password=erp_pass&sslmode=require&TimeZone=Asia/Ho_Chi_Minh

cors:
  AllowOrigins: [ 'http://erp.dev.thd.com:5173', 'https://192.168.1.58', 'http://192.168.1.58', 'https://192.168.1.58:443' ]
