server:
  AppVersion: 1.0.0
  Port: localhost:8080
  SSL: true



postgres:
  DBSource: postgresql://neondb_owner:npg_tkKa6Gfspq7w@ep-proud-sound-a49dcdxx-pooler.us-east-1.aws.neon.tech/neondb?sslmode=require


cors:
  AllowOrigins: ['http://localhost:5173']