variables:
  BE_CONTAINER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}-backend
  FE_CONTAINER_IMAGE: ${REGISTRY_URL}/${REGISTRY_PROJECT}/${CI_PROJECT_NAME}-frontend
  UAT_CONTAINER_TAG: ${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}

stages:
  - trigger
  - deploy


#### Trigger Stage

trigger-backend:
  stage: trigger
  rules:
    - changes:
        - backend/**
  trigger:
    include: backend/.gitlab-ci.yml
    strategy: depend

trigger-frontend:
  stage: trigger
  rules:
    - changes:
        - frontend/**
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend


#### Deploy Stage

deploy-uat:
  stage: deploy
  script:
    - echo "deploy to uat version $CI_COMMIT_TAG"
    - cp sample.env .env
    - FE_CONTAINER_IMAGE=$FE_CONTAINER_IMAGE BE_CONTAINER_IMAGE=$BE_CONTAINER_IMAGE CONTAINER_TAG=${UAT_CONTAINER_TAG} docker compose -f ./deploys/docker-compose.uat.yml up -d --remove-orphans
    - sleep 10
    - docker compose -f ./deploys/docker-compose.uat.yml ps
  environment:
    name: staging
    url: http://10.57.70.12:3000/
    on_stop: stop_uat
  tags:
    - uat
  rules:
    - if: '$CI_COMMIT_TAG =~ /^uat_/'
    - when: manual

stop_uat:
  stage: deploy
  script:
    - cp sample.env .env
    - FE_CONTAINER_IMAGE=$FE_CONTAINER_IMAGE BE_CONTAINER_IMAGE=$BE_CONTAINER_IMAGE CONTAINER_TAG=${UAT_CONTAINER_TAG} docker compose -f ./deploys/docker-compose.uat.yml down
  environment:
    name: staging
    url: http://10.57.70.12:3000/
    action: stop
  tags:
    - uat
  when: manual
  rules:
    - if: '$CI_COMMIT_TAG =~ /^uat_/'
      when: manual

deploy-prod:
  stage: deploy
  script: echo "deploy to prod version $CI_COMMIT_TAG"
  environment:
    name: production
  rules:
    - if: '$CI_COMMIT_TAG'
      when: manual
    - when: never
