include:
  - template: Security/SAST.gitlab-ci.yml

stages:
    - build
    - test
    - deploy
    - checklog

build:
    stage: build
    script:
        - echo "hello"
        - whoami
        - pwd
        - ls
