include:
  - template: Security/SAST.gitlab-ci.yml

stages:
    - lint
    - test
    - build
    - deploy

lint:
  stage: lint
  image: golangci/golangci-lint:v1.56
  script:
    - golangci-lint run --timeout 5m

build:
  stage: build
  script:
    - echo "build"

deploy:
  stage: deploy
  script: echo "deploy"
