import {
    Dialog,
    DialogContent,
    DialogHeader,
    DialogTitle,
    DialogTrigger,
} from "@/components/ui/dialog";
import {Loader2, Plus} from "lucide-react";
import {z} from "zod";
import {zodResolver} from "@hookform/resolvers/zod";
import {useForm} from "react-hook-form";
import {Button} from "@/components/ui/button";
import {
    Form,
    FormControl,
    FormField,
    FormItem,
    FormLabel,
    FormMessage,
} from "@/components/ui/form";
import {Input} from "@/components/ui/input";
import {useEffect, useState} from "react";
import {useMutation} from "@tanstack/react-query";
import {toast} from "sonner";
import type {Allowance} from "@/types/allowance";
import {
    createAllowanceApi,
    updateAllowanceApi,
} from "@/apis/allowance.api";
import {
    Select,
    SelectContent,
    SelectItem,
    SelectTrigger,
    SelectValue,
} from "@/components/ui/select";

const formSchema = z.object({
    allowance_name: z.string().min(1, "Tên phụ cấp không được để trống"),
    amount: z.number().min(0, "Số tiền không được âm"),
    unit: z.string().min(1, "Đơn vị không được để trống"),
    tax: z.string().min(1, "Vui lòng chọn có hoặc không"),
});

type Props = {
    editBtn?: React.ReactNode;
    data?: Allowance;
    type?: "edit";
    refetch?: () => void;
};

const AllowanceForm = ({editBtn, data, type, refetch}: Props) => {
    const [open, setOpen] = useState(false);

    const {mutateAsync: createAllowance, isPending: pendingCreate} = useMutation({
        mutationFn: (payload: Omit<Allowance, "id" | "is_deleted" | "created_date">) =>
            createAllowanceApi({
                ...payload,
                id: "", // Will be generated by backend
                is_deleted: false,
                created_date: new Date().toISOString(),
            }),
        onSuccess: () => {
            refetch?.();
            setOpen(false);
            toast.success("Tạo phụ cấp thành công");
            form.reset();
        },
        onError: (error: any) => {
            toast.error(error.message);
        },
    });

    const {mutateAsync: updateAllowance, isPending: pendingUpdate} = useMutation({
        mutationFn: ({id, payload}: { id: string; payload: Partial<Allowance> }) =>
            updateAllowanceApi(id, payload),
        onSuccess: () => {
            refetch?.();
            setOpen(false);
            toast.success("Cập nhật phụ cấp thành công");
            form.reset();
        },
        onError: (error: any) => {
            toast.error(error.message);
        },
    });

    const form = useForm<z.infer<typeof formSchema>>({
        resolver: zodResolver(formSchema),
        defaultValues: {
            allowance_name: "",
            amount: 0,
            unit: "",
            tax: "No", // Default to "No"
        },
    });

    useEffect(() => {
        if (data) {
            form.reset({
                allowance_name: data.allowance_name,
                amount: data.amount,
                unit: data.unit,
                tax: data.tax ? "Yes" : "No", // Convert boolean to "Yes"/"No"
            });
        }
    }, [data]);

    async function onSubmit(values: z.infer<typeof formSchema>) {
        try {
            const payload = {
                ...values,
                tax: values.tax === "Yes", // Convert "Yes"/"No" back to boolean
            };

            if (type === "edit") {
                await updateAllowance({
                    id: data?.id || "",
                    payload,
                });
            } else {
                await createAllowance(payload);
            }
        } catch (error) {
            console.error("Error submitting form:", error);
        }
    }

    return (
        <Dialog open={open} onOpenChange={setOpen}>
            <DialogTrigger>
                {editBtn ? (
                    editBtn
                ) : (
                    <Button>
                        <Plus/>
                        Thêm phụ cấp
                    </Button>
                )}
            </DialogTrigger>
            <DialogContent className="md:max-w-2xl">
                <div className="flex md:flex-row flex-col gap-3 justify-between items-center w-full p-5">
                    <DialogHeader>
                        {type === "edit" ? (
                            <DialogTitle>Chỉnh sửa phụ cấp</DialogTitle>
                        ) : (
                            <DialogTitle>Thêm phụ cấp</DialogTitle>
                        )}
                    </DialogHeader>
                    {
                        data?.id ? (
                            <div className="border p-3 w-fit rounded-lg border-black">
                                {data?.id}
                            </div>
                        ) :
                            null
                    }

                </div>
                <Form {...form}>
                    <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-4">
                        <div className="grid grid-cols-2 gap-4">
                            <FormField
                                control={form.control}
                                name="allowance_name"
                                render={({field}) => (
                                    <FormItem>
                                        <FormLabel>Tên phụ cấp</FormLabel>
                                        <FormControl>
                                            <Input placeholder="Nhập tên phụ cấp" {...field} />
                                        </FormControl>
                                        <FormMessage/>
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="amount"
                                render={({field}) => (
                                    <FormItem>
                                        <FormLabel>Số tiền</FormLabel>
                                        <FormControl>
                                            <Input
                                                type="number"
                                                min="0"
                                                placeholder="Nhập số tiền"
                                                {...field}
                                                onChange={(e) => field.onChange(parseInt(e.target.value) || 0)}
                                            />
                                        </FormControl>
                                        <FormMessage/>
                                    </FormItem>
                                )}
                            />
                        </div>

                        <div className="grid grid-cols-2 gap-4">
                            <FormField
                                control={form.control}
                                name="unit"
                                render={({field}) => (
                                    <FormItem>
                                        <FormLabel>Đơn vị</FormLabel>
                                        <Select onValueChange={field.onChange} value={field.value}>
                                            <FormControl>
                                                <SelectTrigger>
                                                    <SelectValue placeholder="Chọn đơn vị"/>
                                                </SelectTrigger>
                                            </FormControl>
                                            <SelectContent>
                                                <SelectItem value="VND">VND</SelectItem>
                                                <SelectItem value="USD">USD</SelectItem>
                                                <SelectItem value="EUR">EUR</SelectItem>
                                                <SelectItem value="JPY">JPY</SelectItem>
                                                <SelectItem value="GBP">GBP</SelectItem>
                                            </SelectContent>
                                        </Select>
                                        <FormMessage/>
                                    </FormItem>
                                )}
                            />
                            <FormField
                                control={form.control}
                                name="tax"
                                render={({field}) => (
                                    <FormItem>
                                        <FormLabel>Chịu thuế</FormLabel>
                                        <Select onValueChange={field.onChange} value={field.value}>
                                            <FormControl>
                                                <SelectTrigger>
                                                    <SelectValue placeholder="Chọn trạng thái"/>
                                                </SelectTrigger>
                                            </FormControl>
                                            <SelectContent>
                                                <SelectItem value="Yes">Có</SelectItem>
                                                <SelectItem value="No">Không</SelectItem>
                                            </SelectContent>
                                        </Select>
                                        <FormMessage/>
                                    </FormItem>
                                )}
                            />
                        </div>

                        <Button
                            type="submit"
                            className="w-full mt-4"
                            disabled={pendingCreate || pendingUpdate}
                        >
                            {pendingCreate || pendingUpdate ? (
                                <Loader2 className="animate-spin"/>
                            ) : type === "edit" ? (
                                "Cập nhật"
                            ) : (
                                "Thêm"
                            )}
                        </Button>
                    </form>
                </Form>
            </DialogContent>
        </Dialog>
    );
};

export default AllowanceForm;