version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: erp-postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: erp-minio
    command: server --console-address ":9001" /data
    env_file:
      - .env
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

volumes:
  pgdata:
  minio_data:
